function y = ordthres(x,s)
% ORDTHRES - ordered threshold dithering
% The matrix of thresholds is given by s
% The image x must have dynamic range [0,255]

    N = max(s(:))+2;    % the number of gray levels generated by the matrix
    D = 255/(N-1);      % quantization step
    
    % adjust the matrix to the dynamic range of the image
    s = D*(s+0.5);
    
    % pave the image plane with the matrix of thresholds
    sz_x = size(x);
    sz_s = size(s);
    S=repmat(s,ceil(sz_x(1:2)./sz_s));
    S=S(1:sz_x(1),1:sz_x(2)); % limit to the image size
    y = x >= S;         % thresholding

